FROM golang:1.25

WORKDIR /app

# 開発ツールのインストール
RUN go install github.com/air-verse/air@latest
RUN go install github.com/swaggo/swag/cmd/swag@latest
RUN go install go.uber.org/mock/mockgen@latest

ENV PATH="/go/bin:${PATH}"

COPY go.mod go.sum* ./
RUN go mod download || true

COPY . .

EXPOSE 8080

# devcontainerではシェルを保持
CMD ["/bin/bash"]
