FROM golang:1.25.6

WORKDIR /app

RUN go install github.com/air-verse/air@latest
RUN go install github.com/swaggo/swag/cmd/swag@latest
RUN go install go.uber.org/mock/mockgen@latest

ENV PATH="/go/bin:${PATH}"

COPY go.mod go.sum* ./
RUN go mod download || true

COPY . .

EXPOSE 8080

RUN go mod tidy